### ISSUE TITLE
Builds failing in github actions with `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by KholdStare** [foundry-rs/foundry-toolchain#15]
We use the [foundry-toolchain](https://github.com/foundry-rs/foundry-toolchain) github action in our CI and it started failing recently with failures like this:

```
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by forge)
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by forge)
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by forge)
```

Is there a problem with the nightly release?

**Comment by zaqk** [comment]
having the same issue

**Comment by KholdStare** [comment]
Head over to https://github.com/foundry-rs/foundry/issues/3827 - the foundry guys are working through it. Seems like it's due to migration of Github Actions runners from `ubuntu-20.04` to `ubuntu-22.04`. The short-term fix is to pin your build job to `runs-on: ubuntu-22.04` . I would follow the other thread to see the long-term solution

**Comment by gakonst** [comment]
Correct, closing and let's consolidate.
