### ISSUE TITLE
Disable Cache

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry-toolchain#22]
we use our own cache solution we dont want to use this one, pls add opt-in

**Comment by gakonst** [comment]
Could you link to your own cache solution?

**Comment by sambacha** [comment]
Its closed source though I can see about opening it up. The cache proxy we are using is a cloudflare worker that does rewriting for requests and responses based on what exactly we are testing. It could live within a github action though the network overhead is the same as cache persistence is hosted on azure (i think?).

In the mean time you can additionally checkout Apache Tuweni, it has built in JSON RPC cache service that is configured by TOML 

https://tuweni.apache.org/tutorials/apps/jsonrpc/

https://github.com/apache/incubator-tuweni/blob/main/jsonrpc-app/src/main/kotlin/org/apache/tuweni/jsonrpc/app/JSONRPCApp.kt

**Comment by PaulRBerg** [comment]
@sambacha you can now disable the cache like this:

```yml
- name: Install Foundry
  uses: foundry-rs/foundry-toolchain@v1
  with:
    cache: false
```

**Comment by sambacha** [comment]
> @sambacha you can now disable the cache like this:
> 
> 
> 
> ```yml
> 
> - name: Install Foundry
> 
>   uses: foundry-rs/foundry-toolchain@v1
> 
>   with:
> 
>     cache: false
> 
> ```

:)))))
