### ISSUE TITLE
Update "v1" branch with "v1.0.8"

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry-toolchain#23]
@gakonst has shipped v1.0.8 to npm, and @mds1 has [announced](https://twitter.com/msolomon44/status/1614027496424607745) the caching functionality on Twitter, but we haven't yet updated the `v1` branch to point to the latest HEAD.

This means that anyone using the `v1` ref in their GitHub Action workflow will not get caching:

```yaml
foundry-rs/foundry-toolchain@v1
```

This is the recommended way to install the GItHub Action in the README.

**Comment by gakonst** [comment]
The V1 tag has been moved to latest https://github.com/foundry-rs/foundry-toolchain/tree/v1
