### ISSUE TITLE
Option to configure rpc caching

### ISSUE THREAD

**Issue by fubhy** [foundry-rs/foundry-toolchain#33]
When running multiple github workflows or jobs in parallel the current cache config is a bit problematic. Since only a single workflow can obtain write access to the cache and the cache key is configured with the platform and github sha only and does not include the job identifier (or a way to configure the cache key or a cache key suffix), it effectively means that, non-deterministically, one of the jobs wins and the other basically never has a cache stored for it.

Hence, it would be great if we can:

1. Add the job id to the cache key
2. Additionally allow users to pass config to override the cache key entirely or disable caching and handle it yourself.

**Comment by penandlim** [comment]
+1 on the adding job ID to the cache primary key. Adding it to the restore keys would be helpful as well.
Would allow you to have different caches per job.

```javascript
const primaryKey = PLATFORM + "-foundry-chain-fork-" + github.context.job + "-" + github.context.sha;
const restoreKeys = [
    PLATFORM + "-foundry-chain-fork-" + github.context.job + "-",
    PLATFORM + "-foundry-chain-fork-"
];
```

**Comment by onbjerg** [comment]
Feel free to open a PR - let's add the job & a custom cache key
