### ISSUE TITLE
ARM releases for action

### ISSUE THREAD

**Issue by 0xAlcibiades** [foundry-rs/foundry-toolchain#42]
This action assumes

```js
function mapArch(arch) {
  const mappings = {
    x32: "386",
    x64: "amd64",
  };

  return mappings[arch] || arch;
}
```

However, many developers and much prod infra is now moving to ARM - and the foundry toolchain also exists for ARM. The toolchain check should additionally check for ARM - as it is broken there.

**Comment by 0xAlcibiades** [comment]
https://github.com/0xAlcibiades/foundry-toolchain/commit/623f10ae808bf952efad0eca8992f5c8a1b8347d

Here is a very sloppy hotfix - but this could be done better.

**Comment by onbjerg** [comment]
Are you actually using an ARM runner? `os.arch()` in Node.js should not return `x64` if you are on ARM, it should return `arm` or `arm64`. See here: https://nodejs.org/api/os.html#osarch
