### ISSUE TITLE
Anvil Support

### ISSUE THREAD

**Issue by avniculae** [foundry-rs/foundry-toolchain#52]
Does this not install anvil?

**Comment by Confucian-e** [comment]
Same Question

**Comment by zerosnacks** [comment]
Anvil is supported by `foundry-toolchain`, we use it in `alloy-rs/alloy`: https://github.com/alloy-rs/alloy/blob/0bbe0326a5558ec3163b8ec6b9e7acf944abaa22/.github/workflows/ci.yml#L44-L47
